// Source Token & Field Registry for USER_AGREEMENT_V1
// Single source of truth for Wizard inputs, data validation, token substitution, preview & PDF rendering

export interface AgreementSourceField {
  key: string
  label: string
  sourceLocation: string
  sourceType: 'database' | 'calculated' | 'manual' | 'fixed'
  requiredBeforeGeneration: boolean
  fallback?: string
  snapshotField: string
}

export const USER_AGREEMENT_SOURCE_REGISTRY: AgreementSourceField[] = [
  // Preamble & Primary Lessee
  {
    key: 'agreement_number',
    label: 'Agreement Number',
    sourceLocation: 'Preamble + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'agreement_number',
  },
  {
    key: 'agreement_date',
    label: 'Agreement Date',
    sourceLocation: 'Preamble + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'agreement_date',
  },
  {
    key: 'lessee_full_name',
    label: 'Lessee Full Name',
    sourceLocation: 'Preamble + Schedule + Signatures',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'lessee_snapshot.full_name',
  },
  {
    key: 'lessee_identifier_no',
    label: 'Lessee NIC / Passport Number',
    sourceLocation: 'Preamble + Schedule + Signatures',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'lessee_snapshot.identifier_no',
  },
  {
    key: 'lessee_address',
    label: 'Lessee Registered Post Address',
    sourceLocation: 'Preamble + Schedule + Signatures',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'lessee_snapshot.address',
  },
  {
    key: 'lessee_mobile',
    label: 'Lessee Mobile Number',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'lessee_snapshot.mobile',
  },
  {
    key: 'lessee_email',
    label: 'Lessee Email Address',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'lessee_snapshot.email',
  },
  {
    key: 'lessee_driving_license',
    label: 'Lessee Driving License Number',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'lessee_snapshot.driving_license_number',
  },

  // Rental & Period
  {
    key: 'rental_start_at',
    label: 'Rental Start Date & Time',
    sourceLocation: 'Clause 1 + Clause 2 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_start_at',
  },
  {
    key: 'rental_end_at',
    label: 'Rental End Date & Time',
    sourceLocation: 'Clause 1 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_end_at',
  },
  {
    key: 'rental_period_days',
    label: 'Rental Period (Days)',
    sourceLocation: 'Clause 1 + Schedule',
    sourceType: 'calculated',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_snapshot.rental_period_days',
  },
  {
    key: 'daily_rental_rate',
    label: 'Daily Rental Tariff (LKR)',
    sourceLocation: 'Clause 2 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_snapshot.daily_rental_rate',
  },
  {
    key: 'monthly_rental_rate',
    label: 'Monthly Rental Tariff (LKR)',
    sourceLocation: 'Clause 2 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: '0',
    snapshotField: 'rental_snapshot.monthly_rental_rate',
  },
  {
    key: 'due_date_day',
    label: 'Monthly Rent Payment Due Day',
    sourceLocation: 'Clause 2',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '1st',
    snapshotField: 'agreement_variables_snapshot.due_date_day',
  },
  {
    key: 'security_deposit',
    label: 'Security Deposit (LKR)',
    sourceLocation: 'Clause 2 + Clause 3 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_snapshot.security_deposit',
  },
  {
    key: 'extra_km_rate',
    label: 'Extra Kilometer Rate (LKR)',
    sourceLocation: 'Clause 2 + Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'rental_snapshot.extra_km_rate',
  },
  {
    key: 'advance_paid',
    label: 'Advance Rental Paid (LKR)',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: '0',
    snapshotField: 'rental_snapshot.advance_paid',
  },
  {
    key: 'delivery_fee',
    label: 'Vehicle Delivery Fee (LKR)',
    sourceLocation: 'Schedule',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '0',
    snapshotField: 'rental_snapshot.delivery_fee',
  },
  {
    key: 'pickup_fee',
    label: 'Vehicle Pickup Fee (LKR)',
    sourceLocation: 'Schedule',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '0',
    snapshotField: 'rental_snapshot.pickup_fee',
  },

  // Vehicle Details
  {
    key: 'vehicle_make_model',
    label: 'Vehicle Make & Model',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'vehicle_snapshot.make_model',
  },
  {
    key: 'vehicle_registration_number',
    label: 'Vehicle Registration Number',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'vehicle_snapshot.registration_number',
  },
  {
    key: 'vehicle_color',
    label: 'Vehicle Color',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: 'White',
    snapshotField: 'vehicle_snapshot.color',
  },
  {
    key: 'vehicle_fuel_type',
    label: 'Vehicle Fuel Type',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: false,
    fallback: 'Petrol',
    snapshotField: 'vehicle_snapshot.fuel_type',
  },
  {
    key: 'vehicle_pickup_odometer',
    label: 'Handover Odometer Reading (KM)',
    sourceLocation: 'Schedule',
    sourceType: 'database',
    requiredBeforeGeneration: true,
    snapshotField: 'vehicle_snapshot.pickup_odometer',
  },

  // Nominated Drivers, Lessor Rep, Lessee 02, Witnesses
  {
    key: 'nominated_drivers',
    label: 'Nominated Drivers List',
    sourceLocation: 'Clause 5 + Drivers Table',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: 'Self Drive by Lessee',
    snapshotField: 'nominated_drivers_snapshot',
  },
  {
    key: 'lessor_representative_name',
    label: 'Lessor Representative Name',
    sourceLocation: 'Signatures Section',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: 'Authorized Officer',
    snapshotField: 'lessor_representative_snapshot.name',
  },
  {
    key: 'lessor_representative_nic',
    label: 'Lessor Representative NIC',
    sourceLocation: 'Signatures Section',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'lessor_representative_snapshot.nic',
  },
  {
    key: 'witness_1_name',
    label: 'Witness 1 Name',
    sourceLocation: 'In the Presence of Section',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'witnesses_snapshot.witness_1.name',
  },
  {
    key: 'witness_2_name',
    label: 'Witness 2 Name',
    sourceLocation: 'In the Presence of Section',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'witnesses_snapshot.witness_2.name',
  },
  {
    key: 'special_notes',
    label: 'Special Notes',
    sourceLocation: 'Schedule',
    sourceType: 'manual',
    requiredBeforeGeneration: false,
    fallback: '',
    snapshotField: 'special_notes',
  },
]
