export interface NavigationItem {
  id: string
  label: string
  href: string
  iconName: string
  sectionId: string
  requiredRoles: string[]
  enabled: boolean
  comingSoon?: boolean
  badge?: string
  keywords?: string[]
}

export interface NavigationSection {
  id: string
  title: string
  items: NavigationItem[]
}

export const ALL_ROLES = [
  'owner',
  'admin',
  'manager',
  'booking_staff',
  'operations_staff',
  'marketing_staff',
  'finance_staff',
  'driver',
  'viewer',
]

export const NAVIGATION_CONFIG: NavigationSection[] = [
  {
    id: 'overview',
    title: 'OVERVIEW',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        href: '/dashboard',
        iconName: 'LayoutDashboard',
        sectionId: 'overview',
        requiredRoles: ALL_ROLES,
        enabled: true,
        keywords: ['overview', 'dashboard', 'home', 'kpi', 'revenue'],
      },
      {
        id: 'analytics',
        label: 'Analytics',
        href: '/dashboard/reports',
        iconName: 'ChartNoAxesCombined',
        sectionId: 'overview',
        requiredRoles: ['owner', 'admin', 'manager', 'finance_staff', 'marketing_staff', 'viewer'],
        enabled: true,
        keywords: ['analytics', 'metrics', 'performance', 'charts'],
      },
    ],
  },
  {
    id: 'sales_rentals',
    title: 'SALES & RENTALS',
    items: [
      {
        id: 'quotations',
        label: 'Quotations',
        href: '/dashboard/quotations',
        iconName: 'FileText',
        sectionId: 'sales_rentals',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'viewer'],
        enabled: true,
        keywords: ['quotations', 'quotes', 'estimates', 'proforma'],
      },
      {
        id: 'bookings',
        label: 'Bookings',
        href: '/dashboard/bookings',
        iconName: 'CalendarCheck',
        sectionId: 'sales_rentals',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'operations_staff', 'viewer'],
        enabled: true,
        keywords: ['bookings', 'reservations', 'trips', 'calendar'],
      },
      {
        id: 'agreements',
        label: 'Agreements',
        href: '/dashboard/agreements',
        iconName: 'ScrollText',
        sectionId: 'sales_rentals',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'operations_staff', 'finance_staff', 'viewer'],
        enabled: true,
        keywords: ['agreements', 'contracts', 'rental agreement', 'terms'],
      },
    ],
  },
  {
    id: 'crm',
    title: 'CRM',
    items: [
      {
        id: 'customers',
        label: 'Customers',
        href: '/dashboard/customers',
        iconName: 'Users',
        sectionId: 'crm',
        requiredRoles: ALL_ROLES,
        enabled: true,
        keywords: ['customers', 'clients', 'hirers', 'directory'],
      },
      {
        id: 'leads',
        label: 'Leads & Enquiries',
        href: '/dashboard/leads',
        iconName: 'UserRoundSearch',
        sectionId: 'crm',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        badge: 'SOON',
        keywords: ['leads', 'enquiries', 'inquiries', 'pipeline'],
      },
    ],
  },
  {
    id: 'fleet',
    title: 'FLEET',
    items: [
      {
        id: 'vehicles',
        label: 'Vehicles',
        href: '/dashboard/vehicles',
        iconName: 'Car',
        sectionId: 'fleet',
        requiredRoles: ALL_ROLES,
        enabled: true,
        keywords: ['vehicles', 'cars', 'fleet', 'automobiles'],
      },
      {
        id: 'drivers',
        label: 'Drivers',
        href: '/dashboard/drivers',
        iconName: 'UserRound',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'finance_staff', 'viewer'],
        enabled: true,
        keywords: ['drivers', 'chauffeurs', 'roster', 'staff'],
      },
      {
        id: 'vehicle_owners',
        label: 'Vehicle Owners',
        href: '/dashboard/fleet/owners',
        iconName: 'UserCog',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['owners', 'partners', 'suppliers', 'third party'],
      },
      {
        id: 'inspections',
        label: 'Inspections',
        href: '/dashboard/maintenance/inspections',
        iconName: 'ClipboardCheck',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['inspections', 'checklists', 'condition', 'condition report'],
      },
      {
        id: 'maintenance',
        label: 'Maintenance',
        href: '/dashboard/maintenance',
        iconName: 'Wrench',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'viewer'],
        enabled: true,
        keywords: ['maintenance', 'repairs', 'servicing', 'garage'],
      },
      {
        id: 'fuel',
        label: 'Fuel Tracking',
        href: '/dashboard/fleet/fuel',
        iconName: 'Fuel',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'finance_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['fuel', 'petrol', 'diesel', 'consumption', 'mileage'],
      },
      {
        id: 'gps',
        label: 'Live GPS',
        href: '/dashboard/fleet',
        iconName: 'MapPin',
        sectionId: 'fleet',
        requiredRoles: ['owner', 'admin', 'manager', 'operations_staff', 'viewer'],
        enabled: true,
        keywords: ['gps', 'tracking', 'location', 'live map'],
      },
    ],
  },
  {
    id: 'finance',
    title: 'FINANCE',
    items: [
      {
        id: 'earnings',
        label: 'Earnings',
        href: '/dashboard/reports/earnings',
        iconName: 'TrendingUp',
        sectionId: 'finance',
        requiredRoles: ['owner', 'admin', 'manager', 'finance_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['earnings', 'revenue', 'profit', 'income'],
      },
      {
        id: 'expenses',
        label: 'Expenses',
        href: '/dashboard/expenses',
        iconName: 'ReceiptText',
        sectionId: 'finance',
        requiredRoles: ['owner', 'admin', 'manager', 'finance_staff', 'viewer'],
        enabled: true,
        keywords: ['expenses', 'spending', 'costs', 'outflow'],
      },
      {
        id: 'invoices',
        label: 'Invoices',
        href: '/dashboard/invoices',
        iconName: 'FileSpreadsheet',
        sectionId: 'finance',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'finance_staff', 'viewer'],
        enabled: true,
        keywords: ['invoices', 'bills', 'billing', 'accounts receivable'],
      },
      {
        id: 'receipts',
        label: 'Payments & Receipts',
        href: '/dashboard/receipts',
        iconName: 'WalletCards',
        sectionId: 'finance',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'finance_staff', 'viewer'],
        enabled: true,
        keywords: ['receipts', 'payments', 'vouchers', 'cashier'],
      },
    ],
  },
  {
    id: 'marketing',
    title: 'MARKETING',
    items: [
      {
        id: 'marketing_calendar',
        label: 'Content Calendar',
        href: '/dashboard/marketing/calendar',
        iconName: 'CalendarDays',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        keywords: ['calendar', 'content', 'marketing', 'schedule'],
      },
      {
        id: 'campaigns',
        label: 'Campaigns',
        href: '/dashboard/marketing/campaigns',
        iconName: 'Megaphone',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        keywords: ['campaigns', 'promotions', 'ads', 'marketing'],
      },
      {
        id: 'content_planner',
        label: 'Content Planner',
        href: '/dashboard/marketing/planner',
        iconName: 'ListTodo',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['planner', 'ideas', 'strategy', 'backlog'],
      },
      {
        id: 'content_library',
        label: 'Content Library',
        href: '/dashboard/marketing/library',
        iconName: 'Images',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['library', 'assets', 'photos', 'media'],
      },
      {
        id: 'social_media',
        label: 'Social Media',
        href: '/dashboard/marketing/social',
        iconName: 'Share2',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['social', 'facebook', 'instagram', 'posts'],
      },
      {
        id: 'marketing_analytics',
        label: 'Marketing Analytics',
        href: '/dashboard/marketing/analytics',
        iconName: 'ChartSpline',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['reach', 'conversion', 'leads', 'analytics'],
      },
      {
        id: 'offers',
        label: 'Offers & Promotions',
        href: '/dashboard/marketing/offers',
        iconName: 'Tags',
        sectionId: 'marketing',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['offers', 'discounts', 'vouchers', 'promo'],
      },
    ],
  },
  {
    id: 'reports',
    title: 'REPORTS',
    items: [
      {
        id: 'reports_center',
        label: 'Reports Center',
        href: '/dashboard/reports',
        iconName: 'FileBarChart',
        sectionId: 'reports',
        requiredRoles: ['owner', 'admin', 'manager', 'finance_staff', 'marketing_staff', 'viewer'],
        enabled: true,
        keywords: ['reports', 'pdf export', 'summaries', 'statements'],
      },
      {
        id: 'ai_reports',
        label: 'AI Reports',
        href: '/dashboard/ai-tools',
        iconName: 'Sparkles',
        sectionId: 'reports',
        requiredRoles: ['owner', 'admin', 'marketing_staff', 'viewer'],
        enabled: true,
        keywords: ['ai', 'ai tools', 'insights', 'intelligence'],
      },
    ],
  },
  {
    id: 'communication',
    title: 'COMMUNICATION',
    items: [
      {
        id: 'reminders',
        label: 'Reminders',
        href: '/dashboard/reminders',
        iconName: 'Bell',
        sectionId: 'communication',
        requiredRoles: ALL_ROLES,
        enabled: true,
        comingSoon: true,
        keywords: ['reminders', 'notifications', 'alerts'],
      },
      {
        id: 'whatsapp',
        label: 'WhatsApp',
        href: '/dashboard/communication/whatsapp',
        iconName: 'MessageCircle',
        sectionId: 'communication',
        requiredRoles: ALL_ROLES,
        enabled: true,
        comingSoon: true,
        keywords: ['whatsapp', 'messaging', 'chats', 'send message'],
      },
      {
        id: 'sms',
        label: 'SMS',
        href: '/dashboard/communication/sms',
        iconName: 'MessageSquareText',
        sectionId: 'communication',
        requiredRoles: ['owner', 'admin', 'manager', 'booking_staff', 'operations_staff', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['sms', 'text message', 'alerts'],
      },
    ],
  },
  {
    id: 'portals',
    title: 'PORTALS',
    items: [
      {
        id: 'customer_portal',
        label: 'Customer Portal',
        href: '/dashboard/portals/customer',
        iconName: 'UserRoundCheck',
        sectionId: 'portals',
        requiredRoles: ALL_ROLES,
        enabled: true,
        comingSoon: true,
        keywords: ['portal', 'customer app', 'self service'],
      },
      {
        id: 'driver_portal',
        label: 'Driver Portal',
        href: '/dashboard/portals/driver',
        iconName: 'BadgeCheck',
        sectionId: 'portals',
        requiredRoles: ['owner', 'admin', 'operations_staff', 'driver', 'viewer'],
        enabled: true,
        comingSoon: true,
        keywords: ['driver app', 'mobile portal', 'duty roster'],
      },
      {
        id: 'owner_portal',
        label: 'Owner Portal',
        href: '/dashboard/portals/owner',
        iconName: 'ShieldCheck',
        sectionId: 'portals',
        requiredRoles: ['owner'],
        enabled: true,
        comingSoon: true,
        keywords: ['owner portal', 'partner dashboard'],
      },
    ],
  },
  {
    id: 'system',
    title: 'SYSTEM',
    items: [
      {
        id: 'users',
        label: 'Users & Roles',
        href: '/dashboard/users',
        iconName: 'ShieldUser',
        sectionId: 'system',
        requiredRoles: ['owner'],
        enabled: true,
        keywords: ['users', 'roles', 'permissions', 'profiles'],
      },
      {
        id: 'company_settings',
        label: 'Company Settings',
        href: '/dashboard/settings',
        iconName: 'Building2',
        sectionId: 'system',
        requiredRoles: ['owner'],
        enabled: true,
        keywords: ['settings', 'company', 'address', 'preferences'],
      },
      {
        id: 'document_settings',
        label: 'Document Settings',
        href: '/dashboard/document-templates',
        iconName: 'Files',
        sectionId: 'system',
        requiredRoles: ['owner', 'admin', 'manager'],
        enabled: true,
        keywords: ['templates', 'documents', 'pdf settings', 'bank details'],
      },
      {
        id: 'audit_logs',
        label: 'Audit Logs',
        href: '/dashboard/audit-logs',
        iconName: 'ScrollText',
        sectionId: 'system',
        requiredRoles: ['owner', 'admin'],
        enabled: true,
        keywords: ['audit', 'logs', 'activity', 'history', 'security'],
      },
    ],
  },
]

export function getFilteredNavigation(role: string): NavigationSection[] {
  return NAVIGATION_CONFIG.map((sec) => ({
    ...sec,
    items: sec.items.filter((item) => item.enabled && item.requiredRoles.includes(role)),
  })).filter((sec) => sec.items.length > 0)
}

export function getAllNavigationItems(): NavigationItem[] {
  return NAVIGATION_CONFIG.flatMap((sec) => sec.items)
}
